# Generated by Django 5.0 on 2023-12-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dffg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
